networks:
  theNetwork:

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: SA
      SA_PASSWORD: Pa55word2024
    ports:
      - "1433:1433"
    networks:
      - theNetwork

  api_med_dotnet:
    build:
      context: .
      dockerfile: API_med_dotNET/Dockerfile
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - theNetwork
    depends_on:
      - mssql-server
